### ISSUE TITLE
♻️ User 관련 리팩토링

### ISSUE THREAD

**Issue by MinseoKangQ** [Line4thon-Gather/gather_back_end#19]
### 🤓 TODO
- [x] 패키지 이동 (User, UserRepository)
- [x] 서비스 인터페이스 생성
- [x] 서비스 로직 정리

<br>

### ⏱️ 마감기한
- 11/1
