### ISSUE TITLE
🎉 프로젝트 세팅 마무리

### ISSUE THREAD

**Issue by MinseoKangQ** [Line4thon-Gather/gather_back_end#4]
### 🤓 TODO
- [x] 로컬 DB 연결
- [x] security 의존성 추가
- [x] security 관련 세팅
- [x] 권한 체크 오류 커스텀 핸들러 작성
- [x] CustomErrorCode
- [x] 예시 CustomException 클래스 작성
- [x] Swagger 작성
 

<br>

### ⏱️ 마감기한
- 10/22
