### ISSUE TITLE
✨ 요구사항 변경에 의한 추가 개발

### ISSUE THREAD

**Issue by MinseoKangQ** [Line4thon-Gather/gather_back_end#40]
### 🤓 TODO
- [x] 대학생 인증번호 API에 매개변수 추가
- [x] 대학생 인증 관련 필드 업데이트
- [x] 사업자 인증 API 변경 (`사업자등록번호`, `대표자명`, `등록일자`)
- [x] 사업자 인증 API에 매개변수 추가 (`CustomOAuth2User`)
- [x] Swagger 작성

<br>

### ⏱️ 마감기한
- 11/7
