### ISSUE TITLE
♻️ 유저 인증 관련 코드 리팩토링

### ISSUE THREAD

**Issue by MinseoKangQ** [Line4thon-Gather/gather_back_end#44]
### 🤓 TODO
- [x] 이메일 인증번호 전송 API 반환 data `null`로 변경
- [x] 이메일 인증번호 인증 API 반환 data `null`로 변경
- [x] 이메일 인증번호 인증 API 실패 시 예외 던지기 (`AUTH_NUMBER_NOT_MATCH_BAD_REQUEST`)
- [x] 사업자 인증 API 서버 테스트 후 `code`, `message` 필드 변경 필요 여부 판단 & 변경
- [x] 사업자 인증 API 서비스 로직 return 추가
- [x] 정적 팩토리 메소드 `from`, `of` 역할에 맞게 메소드명 수정
- [x] 이메일 인증번호 전송 swagger 업데이트 (200인 경우, 400인 경우, `message`, `code`)
- [x] 이메일 인증번호 인증 swagger 업데이트 (200인 경우, 400인 경우, `message`, `code`)
- [x] 사업자 인증 swagger 업데이트 (200인 경우, 400인 경우, `message`, `code`)
 

<br>

### ⏱️ 마감기한
- 11/4
