### ISSUE TITLE
🔒️ 설정 파일 구성 변경

### ISSUE THREAD

**Issue by MinseoKangQ** [Line4thon-Gather/gather_back_end#8]
### 🤓 TODO
- [x] `yml`, `properties` 파일 정리
- [x] `.gitignore`에 `.env` 파일 추가
- [x] 환경별 `.env` 파일 구성

<br>

### ⏱️ 마감기한
- ex. 10/28
